### PR TITLE
MCPE 1.12 Changes

### PR DESCRIPTION
**Pull request by iiFlamiinBlaze**
Updated to 1.12 packet changes

### CODE REVIEW

**Comment by JuniorYT** [comment]
My thing keeps crashing will that fix that?

**Comment by iiFlamiinBlaze** [comment]
This will fix the crash yes. This plugin does not work in 1.12 rn bc of packet changes so this fixes that.

**Comment by JuniorYT** [comment]
Do you have discord @blazethedev

**Comment by dktapps** [comment]
pls update the API min version to 3.9.0

**Comment by Gianluxx** [comment]
Close it

**Pull request closed without merging**
